services:
  postgres:
    image: postgres:17
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: codepath
      POSTGRES_USER: codepath
      POSTGRES_PASSWORD: codepath
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: on-failure
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "10"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_AUTHENTICATION_SOURCES: "['internal']"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_DISABLE_LOGIN_BANNER: "True"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
      - "15675:15675"
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt && rabbitmq-server"
    environment:
      RABBITMQ_DEFAULT_USER: codepath
      RABBITMQ_DEFAULT_PASS: codepath

volumes:
  postgres_data: